added clear cache

diff --git a/.github/workflows/Main.yml b/.github/workflows/Main.yml
--- a/.github/workflows/Main.yml
+++ b/.github/workflows/Main.yml
@@ -12,13 +12,13 @@ jobs:
     name: Terraform apply
     runs-on: ubuntu-latest
     outputs:
-      INSTANCE_ID: ${steps.outputs.terraform_instance_id.INSTANCE_ID}
+      output1: ${{ steps.terraform_instance_id.outputs.INSTANCE_ID }}
     steps:
     - uses: actions/checkout@v3
       with:
         ref: ${{ github.event.pull_request.head.sha }}
     - name: Configure AWS credentials for pytest
-      uses: aws-actions/configure-aws-credentials@v1
+      uses: aws-actions/configure-aws-credentials@v1-node16
       with:
         aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
@@ -48,11 +48,11 @@ jobs:
         cd terraform/aws_instance
         # terrafrom apply
         terragrunt apply -auto-approve 1> /dev/null
-        echo "INSTANCE_ID=$(terragrunt output -raw instance_id)" >> "GITHUB_OUTPUT"
+        echo "INSTANCE_ID=$(terragrunt output -raw instance_id)" >> "$GITHUB_OUTPUT"
     - uses: actions/cache@v3
       with:
-        path: terraform/aws_instance
-        key: terraform-state
+        path: terraform/aws_instance/*
+        key: terraform-state-${{ steps.terraform_instance_id.outputs.INSTANCE_ID }}
 
   test:
     name: test
@@ -63,9 +63,9 @@ jobs:
         uses: actions/checkout@v3
       - name: test
         env:
-          INSTANCE_ID: ${{ needs.terraform_apply.outputs.INSTANCE_ID }}
+          INSTANCE_ID: ${{ needs.terraform_apply.outputs.output1 }}
         run: |
-          echo ${{ needs.terraform_apply.outputs.INSTANCE_ID }}
+          echo "$INSTANCE_ID"
 
   terraform_destroy:
     name: Terraform Destroy
@@ -77,15 +77,15 @@ jobs:
       with:
         ref: ${{ github.event.pull_request.head.sha }}
     - name: Configure AWS credentials for pytest
-      uses: aws-actions/configure-aws-credentials@v1
+      uses: aws-actions/configure-aws-credentials@v1-node16
       with:
         aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.REGION }}
     - uses: actions/cache@v3
       with:
-        path: terraform/aws_instance
-        key: terraform-state
+        path: terraform/aws_instance/*
+        key: terraform-state-${{ needs.terraform_apply.outputs.output1 }}
     - name: Install terraform and terragrunt
       run: |
         # Install Terrafrom
@@ -103,29 +103,32 @@ jobs:
         ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
         ROLE_NAME: ${{ secrets.ROLE_NAME }}
         REGION_NAME: ${{ secrets.TERRAFORM_REGION }}
-      run: |    
+      run: |
         cd terraform/aws_instance
         # terraform destroy/
         terragrunt destroy -auto-approve 1> /dev/null
-  clear-ccache:
-    runs-on: ubuntu-latest
-    needs: [terraform_destroy]
-    steps:
-      - name: Clear cache
-        uses: actions/github-script@v6
-        with:
-          script: |
-            console.log("About to clear")
-            const caches = await github.rest.actions.getActionsCacheList({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-            })
-            for (const cache of caches.data.actions_caches) {
-              console.log(cache)
-              github.rest.actions.deleteActionsCacheById({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                cache_id: cache.id,
-              })
-            }
-            console.log("Clear completed")
+
+#  clear-ccache:
+#    runs-on: ubuntu-latest
+#    needs: [terraform_destroy]
+#    if: success() || failure()
+#    steps:
+#      - name: Clear cache
+#        uses: actions/github-script@v6
+#        with:
+#          script: |
+#            console.log("About to clear")
+#            const caches = await github.rest.actions.getActionsCacheList({
+#              owner: context.repo.owner,
+#              repo: context.repo.repo,
+#            })
+#            for (const cache of caches.data.actions_caches) {
+#              console.log(cache)
+#            if( cache.key == 'terraform-state')
+#              github.rest.actions.deleteActionsCacheById({
+#                owner: context.repo.owner,
+#                repo: context.repo.repo,
+#                cache_id: cache.id,
+#              })
+#            }
+#            console.log("Clear completed")
